name: m_p_chat
description: M-P Chat Application with real-time messaging and WebRTC calls
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  provider: ^6.1.2
  go_router: ^14.6.2
  http: ^1.2.2
  socket_io_client: ^2.0.3+1
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  flutter_webrtc: ^0.12.3
  audioplayers: ^6.1.0
  # record: ^5.1.2  # Removed due to CMake issues
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  intl: ^0.20.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  mime: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  
  # Dependências básicas para funcionalidades avançadas
  camera: ^0.11.0+2
  video_player: ^2.9.2
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  flutter_sound: ^9.2.13
  wakelock_plus: ^1.2.8
  vibration: ^1.8.4
  flutter_local_notifications: ^17.2.3
  # firebase_core: ^3.6.0
  # firebase_messaging: ^15.1.3
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  contacts_service: ^0.6.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  crypto: ^3.0.5
  encrypt: ^5.0.3
  flutter_markdown: ^0.7.4+1
  syntax_highlight: ^0.2.0
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.1.1
  flutter_swiper_view: ^1.1.8
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  flutter_web_auth_2: ^2.0.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  
flutter_native_splash:
  color: "#2196F3"
  image: assets/images/splash.png
  android: true
  ios: true